### ISSUE TITLE
calendar is not showing anything

### ISSUE THREAD

**Issue by Musickiller** [soapdog/patchfox#86] opened 2021-02-26 23:33 UTC
Hello!

Please help me collect info on this issue, as the only thing I can tell you now is that the calendar is not displaying anything, and there are no error messages in ssb-server console.

Indexing is completed, page reloading does not help.

OS: Windows 10
ssb-server: 15.3.0

**Comment by soapdog** [comment] 2021-05-27 00:44
You mean the _future events_ feature? Or that you can't see any gatherings/events on the timeline?

**Comment by soapdog** [comment] 2021-05-27 01:25
Can't you see future events like this:

<img width="1431" alt="Patchfox - Public 2021-05-27 02-24-32" src="https://user-images.githubusercontent.com/23247/119751287-c3897400-be92-11eb-9257-52e9187d17f3.png">

**Comment by soapdog** [comment] 2021-05-27 01:26
I think that query is broken, or at least incomplete. I'm not sure it shows all future gatherings, but you should be seeing some gatherings at least. Seeing nothing is bad. Can you confirm it is not working?

**Comment by soapdog** [comment] 2021-07-22 12:32
I didn't get feedback on this, and it appears to be working here. I'm going to close this since I can't reproduce the problem.

**Closed by soapdog** 2021-07-22 12:32 UTC
Labels: bug, tier-3
